typedef enum {
    TOKEN_EOF=0,
    TOKEN_ADD,
    TOKEN_MINUS,
    TOKEN_MULTIPLY,
    TOKEN_DIVIDE,
    TOKEN_IDENTIFIER,
    TOKEN_ASSIGN,
    TOKEN_INTEGER,
    TOKEN_FLOAT,
    TOKEN_ERROR
} token_type;
